image: node:12.16.1-buster

pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - npm ci
            - npx eslint .
            - npm audit
            - npm test
          services:
            - mongo
